# Ubuntu generic vars
---
- name: Update repositories cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 360

- name: Update all packages (apt upgrade)
  apt:
    upgrade: dist
    force_apt_get: yes
